# Generated by Django 4.2.7 on 2025-06-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
