# Generated by Django 4.2.7 on 2025-06-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_delete_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
